AWSTemplateFormatVersion: '2010-09-09'
Resources:
  EC2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Action:
          - 'sts:AssumeRole'
        Effect: Allow
        Principal:
          Service:
          - ec2.amazonaws.com
      Policies:
      - PolicyName: kinesis
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Action: 'kinesis:*'
            Effect: Allow
            Resource: '*'

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH, HTTP, and HTTPS access
      VpcId: !ImportValue VPCStackName-VPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 0.0.0.0/0

  EC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.small
      ImageId: ami-0aa7d40eeae50c9a9
      KeyName: mykey
      BlockDeviceMappings:
      - DeviceName: /dev/xvda
        Ebs:
          VolumeSize: 30
          VolumeType: gp2
      NetworkInterfaces:
      - AssociatePublicIpAddress: true
        DeviceIndex: 0
        GroupSet: [!Ref SecurityGroup]
        SubnetId: !ImportValue VPCStackName-PublicSubnet1

  EC2Instance2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.small
      ImageId: ami-0aa7d40eeae50c9a9
      KeyName: mykey
      BlockDeviceMappings:
      - DeviceName: /dev/xvda
        Ebs:
          VolumeSize: 30
          VolumeType: gp2
      NetworkInterfaces:
      - AssociatePublicIpAddress: true
        DeviceIndex: 0
        GroupSet: [!Ref SecurityGroup]
        SubnetId: !ImportValue VPCStackName-PublicSubnet2

  EC2Instance3:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.small
      ImageId: ami-0aa7d40eeae50c9a9
      KeyName: mykey
      BlockDeviceMappings:
      - DeviceName: /dev/xvda
        Ebs:
          VolumeSize: 30
          VolumeType: gp2
      NetworkInterfaces:
      - AssociatePublicIpAddress: true
        DeviceIndex: 0
        GroupSet: [!Ref SecurityGroup]
        SubnetId: !ImportValue VPCStackName-PublicSubnet2
