---
Description: >
       Deploys the necessary compute infrastructure and dependencies to host a Log-Analytics solution on AWS.
       The template creates an IAM role for the EC2 instances, a security group, 
       and three EC2 instances provisioned across two subnets and two availability zones for fault tolerance. 
       The security group allows incoming traffic on ports 22 (SSH), 80 (HTTP), and 443 (HTTPS) 

Parameters:
  EnvironmentName:
    Description: A name that will be prefixed to resource names for easy identification
    Type: String

Resources:
  IAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: web-server-log-ec2
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: kinesisfirehosefullaccess
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Action:
            - firehose:*
            Effect: Allow
            Resource: "*"
      - PolicyName: cloudwatchfullaccess
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Action:
            - autoscaling:Describe*
            - cloudwatch:*
            - logs:*
            - sns:*
            - iam:GetPolicy
            - iam:GetPolicyVersion
            - iam:GetRole
            - oam:ListSinks
            Effect: Allow
            Resource: "*"
          - Action: iam:CreateServiceLinkedRole
            Effect: Allow
            Resource: "arn:aws:iam::*:role/aws-service-role/events.amazonaws.com/AWSServiceRoleForCloudWatchEvents*"
            Condition:
              StringLike:
                iam:AWSServiceName: events.amazonaws.com
          - Action:
            - oam:ListAttachedLinks
            Effect: Allow
            Resource: "arn:aws:oam:*:*:sink/*"

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH, HTTP, and HTTPS access
      VpcId: !ImportValue "${EnvironmentName}-VPCID"
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 0.0.0.0/0

  EC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.small
      ImageId: ami-0aa7d40eeae50c9a9
      KeyName: ~/Desktop/Container.pem
      BlockDeviceMappings:
      - DeviceName: /dev/xvda
        Ebs:
          VolumeSize: 30
          VolumeType: gp2
      IamInstanceProfile: !Ref IAMRole
      NetworkInterfaces:
      - AssociatePublicIpAddress: true
        DeviceIndex: 0
        GroupSet: [!Ref SecurityGroup] 
        SubnetId: !ImportValue "${EnvironmentName}-PUB1-SN"

  EC2Instance2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.small
      ImageId: ami-0aa7d40eeae50c9a9
      KeyName: ~/Desktop/Container.pem
      BlockDeviceMappings:
      - DeviceName: /dev/xvda
        Ebs:
          VolumeSize: 30
          VolumeType: gp2
      IamInstanceProfile: !Ref IAMRole
      NetworkInterfaces:
      - AssociatePublicIpAddress: true
        DeviceIndex: 0
        GroupSet: [!Ref SecurityGroup]
        SubnetId: !ImportValue "${EnvironmentName}-PUB2-SN"

  EC2Instance3:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.small
      ImageId: ami-0aa7d40eeae50c9a9
      KeyName: ~/Desktop/Container.pem
      BlockDeviceMappings:
      - DeviceName: /dev/xvda
        Ebs:
          VolumeSize: 30
          VolumeType: gp2
      IamInstanceProfile: !Ref IAMRole
      NetworkInterfaces:
      - AssociatePublicIpAddress: true
        DeviceIndex: 0
        GroupSet: [!Ref SecurityGroup]
        SubnetId: 
        - Fn::ImportValue: !Sub "${EnvironmentName}-PUB2-SN"
